##
##  Makefile -- Build procedure for sample markdown Apache module
##  Autogenerated via ``apxs -n markdown -g''.
##

builddir=.
top_srcdir=/usr/local/httpd-2.2.17
top_builddir=/usr/local/httpd-2.2.17
include /usr/local/httpd-2.2.17/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib
INCLUDES=-I/home/hamano/local/discount-2.0.4beta4
LDFLAGS=-L/home/hamano/local/discount-2.0.4beta4 -lmarkdown

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_markdown.o mod_markdown.lo mod_markdown.slo mod_markdown.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/markdown

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

